/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.a04t.java_repo.app;

import org.a04t.java_repo.list.LinkedList;

import static org.a04t.java_repo.utilities.StringUtils.join;
import static org.a04t.java_repo.utilities.StringUtils.split;
import static org.a04t.java_repo.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
